#!/bin/bash 

red=`tput setaf 1`
green=`tput setaf 2`
blue=`tput setaf 4`
yellow=`tput setaf 3`

reset=`tput sgr0`

source /usr/local/ostroxt-x86_64_166/environment-setup-corei7-64-ostro-linux 
if [ $? -eq 0 ]
then
  echo "${green}Ostro toolchain init success${reset}"
else
  echo "${red}Toolchain init error, exit ${reset}"
  exit 0 
fi


src_file=cpp-cli.cpp
file_src=/media/sf_vbox_share/$src_file

build_dest=~/realsense_workspace/librealsense/examples/
file_dest=$build_dest$src_file

git_dest=~/realsense_workspace/clisense
git_file_dest=$git_dest/$src_file

echo "${blue}testing $file_src == $file_dest ${reset}"
sudo diff $file_src $file_dest
if [ $? -eq 0 ]
then
  echo "${yellow}No changes in file ...${reset}"
  exit 0 
fi

echo Copy from $file_src to $build_dest
sudo cp $file_src $build_dest
echo Permission change for $file_dest
sudo chown $USER $file_dest
sudo chgrp $USER $file_dest

echo Cpoy make file 
cp make_clisense $git_dest


echo Copy from $file_src to $git_dest
sudo cp $file_src $git_dest
echo Permission change for $git_file_dest
sudo chown $USER $git_file_dest
sudo chgrp $USER $git_file_dest


cd ~/realsense_workspace/librealsense
#sudo make clean
make -j2
if [ $? -eq 0 ]
then
  echo "${green}Make success, Git push ${reset}"
else
  echo "${red}Make error, exit ${reset}"
  exit 0 
fi
#cp -a ~/realsense_workspace/librealsense/bin/. ~/realsense_workspace/clisense/
cp -a ~/realsense_workspace/librealsense/bin/cpp-cli ~/realsense_workspace/clisense/

cp -a -r  ~/realsense_workspace/librealsense/include/ ~/realsense_workspace/clisense/include/
cp -a -r  ~/realsense_workspace/librealsense/lib ~/realsense_workspace/clisense/lib

cd ~/realsense_workspace/clisense/
git config --global user.email "eran.shlomo@intel.com"
git add . 
git commit -m "Auto commit" 
git push https://serans1:er31418817@github.com/serans1/clisense.git

